[theme]
background = "background"
primary = "foreground"
secondary = "dark red"
title = "magenta"
playing = "black"
playing_selected = "green"
playing_bg = "green"
highlight = "foreground"
highlight_bg = "#000000"
error = "#000000"
error_bg = "red"
statusbar = "yellow"
statusbar_progress = "green"
statusbar_bg = "background"
cmdline = "foreground"
cmdline_bg = "background"

statusbar_format = "%artists - %title"

[track_format]
left = "%artist - %title"
center = "%album"
right = "%saved %duration"
